proxmox_node: prox
template_name:  openSuse-Leap-15.6-cloudinit-template

vmid: 2000
vm_name: node-exporter-01

vm_ip: 10.30.30.12
vm_cidr: 24
vm_gateway: 10.30.30.1
vm_dns: 1.1.1.1

storage: local-zfs`
ssh_user: test_1
